---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5d2d092d5894f800114d63f0/webhook/forestry'
sections:
  - type: document
    label: Global Site Config
    path: config.yaml
    templates:
      - config
  - type: document
    label: Social Links
    path: data/social.json
    templates:
      - social
  - type: document
    label: Author
    path: data/author.json
    templates:
      - author
  - type: document
    label: Home
    path: content/_index.md
    templates:
      - home
  - type: document
    label: Blog
    path: content/blog/_index.md
    templates:
      - blog
  - type: document
    label: Portfolio
    path: content/portfolio/_index.md
    templates:
      - portfolio
  - type: document
    label: Contact
    path: content/contact.md
    templates:
      - contact
  - type: directory
    path: content
    match: '**/*'
    exclude: '{posts/**,_index.md,blog/_index.md,portfolio/_index.md,contact.md}'
    label: Pages
    create: all
    templates:
      - page
  - type: directory
    path: content/posts
    match: '**/*'
    label: Posts
    create: all
    templates:
      - post
  - type: directory
    path: content/projects
    match: '**/*'
    label: Projects
    create: all
    templates:
      - project
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
version: '0.47'
